config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'authentication' },
    skip: [:registrations, :passwords]

  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

    authenticated do
      root 'predictions#index'
    end
  end

  resources :faq, only: [:index]
  resources :predictions, only: [:index, :show, :update]
  resources :leaderboards, only: [:index, :new, :create, :edit, :update] do
    collection do
      get 'manage'
    end
    member do
      get 'leave'
      get 'leave_confirm'
      get 'members'
      post 'members_confirm'
    end
    resources :invitations, only: [:new, :create] do
      member do
        get 'accept'
        get 'reject'
      end
    end
  end

  namespace :admin do
    resources :matches, only: [:index, :edit, :update] do
      member do
        get 'points'
      end
    end
    resources :users, only: [:index, :edit, :update]
    resources :leaderboards, only: [:index, :edit, :update, :destroy] do
      get 'delete'
    end
  end

end

app/models/leaderboard.rb
class Leaderboard < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :invitations, dependent: :destroy

  belongs_to :owner, class_name: 'User', foreign_key: :owner_id

  validates :name, presence: true, length: { in: 3..40 }, uniqueness: true
  validates :owner_id, presence: true

  scope :active, -> { where(active: true) }
  scope :closed, -> { where(private: true) }
  scope :opened, -> { where(private: false) }

end

app/controllers/admin/leaderboards_controller.rb
class Admin::LeaderboardsController < ApplicationController
  include DefaultCrud

  before_action :authenticate_user!
  before_action :admin_access?
  before_action :set_active_page, only: [:index]

  private

  def set_active_page
    @active_page = 'admin'
  end

  def entity_parameters
    params.require(:leaderboard).permit(:active, :private)
  end

  def load_entity_object_by_id
    @entity_object = entity.find(params[:leaderboard_id])
  end

  def load_all_entity_objects
    @all_entity_objects = entity.order(:name)
  end

end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_active_page, only: [:index]

  def index
    @prediction_sets = users_with_predictions
  end

  private

  def set_active_page
    @active_page = 'leaderboard'
  end

  def users_with_predictions
    PredictionSet
      .where(tournament: tournament).includes(:user)
      .all
      .select { |set| set.user.active }
      .sort_by { |set| [set.points, set.user.name] }
  end

end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :authenticate_user!
  before_action :leaderboards_active_page, only: [:index]
  before_action :manage_active_page, only: [:manage]
  before_action :load_leaderboard,
    only: [:edit, :update, :leave, :leave_confirm, :members, :members_confirm]
  before_action :leaderboards, only: [:create, :update, :leave_confirm, :members_confirm]

  def index
    @general_board ||= PositionBoard.new
    @boards = current_user.leaderboards.map { |leaderboard| PositionBoard.new(leaderboard) }
  end

  def manage
    @leaderboards = current_user.leaderboards
    @invitations = current_user.invitations
  end

  def new
    @leaderboard = Leaderboard.new
  end

  def create
    leaderboard_params = parameters
    leaderboard_params.merge!(owner_id: current_user.id)
    @leaderboard = Leaderboard.create(leaderboard_params)
    if @leaderboard
      @leaderboard.code = SecureRandom.uuid
      @leaderboard.users << current_user
      @leaderboard.save
    end
  end

  def edit
    @leaderboard = Leaderboard.find(params[:id])
  end

  def update
    if @leaderboard.owner == current_user
      @leaderboard.update(parameters)
    else
      @leaderboard.errors.add(:owner, "Invalid")
    end
  end

  def leave_confirm
    @leaderboard.users.delete(current_user)
  end

  def members_confirm
    if @leaderboard.owner == current_user && params.key?(:users)
      user_ids = params.require(:users).permit(ids: [])['ids']
      user_ids.each { |id| @leaderboard.users.delete(User.find(id)) }
    end
  end

  private

  def leaderboards_active_page
    @active_page = 'leaderboards'
  end

  def manage_active_page
    @active_page = 'manage'
  end

  def parameters
    params.require(:leaderboard).permit(:name, :private)
  end

  def leaderboards
    @leaderboards = current_user.leaderboards
  end

  def load_leaderboard
    @leaderboard ||= Leaderboard.find(params[:id])
  end

end

app/views/leaderboards/_form.html.erb
<div class="modal-body">
  <div class="errors"></div>
  <div class="form-group">
    <%= f.label :name, class: 'control-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
<!--   <div class="form-group">
    <%= f.check_box :private %>
    <%= f.label :private, class: 'control-label' %>
  </div> -->
</div>
<div class="modal-footer">
  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to 'Cancel', '#', class: 'btn btn-default', data: { dismiss: 'modal' } %>
</div>

app/views/leaderboards/_invitations.html.erb
<ul>
  <% invitations.each do |invitation| %>
    <li>
      <%= invitation.leaderboard.owner.name %> invites you to join <%= invitation.leaderboard.name %>
      <%= link_to 'Accept', accept_leaderboard_invitation_path(invitation.leaderboard, invitation),
        remote: true, class: 'btn btn-primary' %>
      <%= link_to 'Reject', reject_leaderboard_invitation_path(invitation.leaderboard, invitation),
        remote: true, class: 'btn btn-danger' %>
    </li>
  <% end %>
</ul>

app/views/leaderboards/_leaderboard.html.erb
<table class="table table-striped table-hover leaderboard-table"
  id="leaderboard-table-<%= board.title.parameterize %>">
  <thead>
    <tr>
      <th>Position</th>
      <th>Name</th>
      <th>Points</th>
    </tr>
  </thead>
  <% board.members.each do |user| %>
    <tr>
      <td class="text-center number">
        <span class="<%= "medal-#{user.index}" %>"><%= user.index %></span>
      </td>
      <td>
        <%= image_tag(user.picture, alt: 'picture', class: 'user-image') %>
        <%= link_to(user.name, prediction_path(user.prediction_set)) %>
      </td>
      <td class="text-center number"><%= user.prediction_set.points %></td>
    </tr>
  <% end %>
</table>

<script type="text/javascript">
  $(document).ready(function() {
     $('#leaderboard-table-<%= board.title.parameterize %>').DataTable({
       retrieve: true,
       // iDisplayLength: 50,
       searching: false,
       lengthChange: false,
       autoWidth: false,
       info: false,
       paging: false,
       columns: [
         { orderable: false },
         { orderable: false },
         { type: "num" }
       ],
       order: [[ 2, "desc" ]]
    });
  });
</script>

app/views/leaderboards/_leave.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Leave Leaderboard</h4>
</div>
<div class="modal-body">
  <ul class="errors"></ul>
  Are you sure that you want to leave: <b><%= leaderboard.name %></b>?
</div>
<div class="modal-footer">
  <%= link_to 'Cancel', '#', class: 'btn btn-default', data: { dismiss: 'modal' } %>
  <%= link_to 'Leave', leave_confirm_leaderboard_path(leaderboard), remote: true,
    class: 'btn btn-danger' %>
</div>

app/views/leaderboards/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">New Leaderboard</h4>
</div>
<div>
  <%= form_for(leaderboard, url: leaderboards_path(leaderboard), remote: true) do |f| %>
    <%= render 'form', f: f, leaderboard: leaderboard %>
  <% end %>
</div>

app/views/leaderboards/_reload.html.erb
$("div.errors").html("")
<% if leaderboard.errors.any? %>
  <% leaderboard.errors.full_messages.each do |message| %>
    $("div.errors").append($("<div class='alert alert-danger'/>").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $("#leaderboards-content")
    .html("<%= escape_javascript(render 'leaderboards', leaderboards: leaderboards) %>");
  $("#leaderboards-manage-modal").modal("hide");
<% end %>

app/views/leaderboards/create.js.erb
<%= render 'reload', leaderboard: @leaderboard, leaderboards: @leaderboards %>

app/views/leaderboards/edit.js.erb
$("#leaderboards-manage-modal-content")
  .html("<%= escape_javascript(render 'edit', leaderboard: @leaderboard) %>");
$("#leaderboards-manage-modal").modal();

app/views/leaderboards/index.html.erb
<div class="container page">
  <h2>
    <span>Leaderboards</span>
  </h2>

  <ul class="nav nav-tabs">
    <li class="nav-item active">
      <a class="nav-link" data-toggle="tab" href="#panel-general" role="tab">General</a>
    </li>
    <% @boards.each do |board| %>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#panel-<%= board.title.parameterize %>" role="tab">
          <%= board.title %>
        </a>
      </li>
    <% end %>
    <li class="nav-item pull-right">
      <%= link_to manage_leaderboards_path do %>
        <span class="glyphicon glyphicon-plus"></span>
      <% end%>
    </li>
  </ul>

  <div class="tab-content card">
    <div class="tab-pane active" id="panel-general" role="tabpanel">
      <%= render 'leaderboard', board: @general_board %>
    </div>
    <% @boards.each do |board| %>
      <div class="tab-pane" id="panel-<%= board.title.parameterize %>" role="tabpanel">
        <%= render 'leaderboard', board: board %>
      </div>
    <% end %>
  </div>

</div>

app/views/leaderboards/leave.js.erb
$("#leaderboards-manage-modal-content")
  .html("<%= escape_javascript(render 'leave', leaderboard: @leaderboard) %>");
$("#leaderboards-manage-modal").modal();

app/views/leaderboards/leave_confirm.js.erb
<%= render 'reload', leaderboard: @leaderboard, leaderboards: @leaderboards %>

app/views/leaderboards/manage.html.erb
<div class="container page">
  <div id="invitations-content">
    <%= render 'invitations', invitations: @invitations %>
  </div>

  <h3>My Leaderboards
    <%= link_to new_leaderboard_path, remote: true, class: 'btn btn-primary pull-right' do %>
      New Leaderboard
    <% end %>
  </h3>

  <div id="leaderboards-content">
    <%= render 'leaderboards', leaderboards: @leaderboards %>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="leaderboards-manage-modal" role="dialog">
    <div class="modal-dialog modal-md">
      <div id="leaderboards-manage-modal-content" class="modal-content"></div>
    </div>
  </div>
</div>

app/views/leaderboards/members.js.erb
$("#leaderboards-manage-modal-content")
  .html("<%= escape_javascript(render 'members', leaderboard: @leaderboard) %>");
$("#leaderboards-manage-modal").modal();

app/views/leaderboards/members_confirm.js.erb
<%= render 'reload', leaderboard: @leaderboard, leaderboards: @leaderboards %>