config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'authentication' },
    skip: [:registrations, :passwords]

  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

    authenticated do
      root 'predictions#index'
    end
  end

  resources :faq, only: [:index]
  resources :predictions, only: [:index, :show, :update]
  resources :leaderboards, only: [:index, :new, :create, :edit, :update] do
    collection do
      get 'manage'
    end
    member do
      get 'leave'
      get 'leave_confirm'
      get 'members'
      post 'members_confirm'
    end
    resources :invitations, only: [:new, :create] do
      member do
        get 'accept'
        get 'reject'
      end
    end
  end

  namespace :admin do
    resources :matches, only: [:index, :edit, :update] do
      member do
        get 'points'
      end
    end
    resources :users, only: [:index, :edit, :update]
    resources :leaderboards, only: [:index, :edit, :update, :destroy] do
      get 'delete'
    end
  end

end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :phase
  belongs_to :team1, class_name: 'Team', optional: true
  belongs_to :team2, class_name: 'Team', optional: true
  belongs_to :tournament

  has_many :predictions

  def score_label
    closed? ? "#{team1_score} - #{team2_score}" : 'vs'
  end

  def last_hour?
    date - 1.hour < Time.current && !closed?
  end

  def closed?
    date - 5.minutes < Time.current
  end

  def valid_scores?
    team1_score.present? && team2_score.present?
  end

  def team1_win?
    team1_score > team2_score
  end

  def team2_win?
    team2_score > team1_score
  end

  def tie?
    team1_score == team2_score
  end

end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < ApplicationController
  include DefaultCrud

  before_action :authenticate_user!
  before_action :admin_access?
  before_action :set_active_page, only: [:index]
  before_action :load_teams, only: [:edit]

  def points
    @match = entity.where(tournament: gc19).includes(:predictions, :phase).find(params[:id])
    Points.new(@match).process
  end

  private

  def set_active_page
    @active_page = 'admin'
  end

  def entity_parameters
    params
      .require(:match)
      .permit(:team1_id, :team2_id, :team1_score, :team2_score, :ready, :team1_label, :team2_label)
  end

  def load_entity_object_by_id
    @entity_object = entity.find(params[:match_id])
  end

  def load_all_entity_objects
    @all_entity_objects = entity.where(tournament: gc19).order(:number)
  end

  def load_teams
    @teams = gc19.teams.all.sort_by(&:name)
  end

end

app/views/admin/matches/_edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Edit Match <%= match.number %></h4>
</div>
<div>
  <%= render 'form', match: match, teams: teams %>
</div>

app/views/admin/matches/_form.html.erb
<%= form_for [:admin, match], remote: true, html: { style: 'display:inline;' } do |f| %>
  <div class="modal-body">
    <div class="errors"></div>
    <div class="row">
      <div class="form-group col-sm-2">
        <span class="control-label">Match: <%= match.number %></span>
      </div>
      <div class="form-group col-sm-5">
        <span class="control-label">Date: <%= local_time(match.date, :long)%></span>
      </div>
      <div class="form-group col-sm-5">
        <span class="control-label">Phase: <%= match.phase.name %></span>
      </div>
    </div>
    <% if match.phase.level == 1 %>
      <div class="row">
        <div class="form-group col-sm-2">
          <span>Score: </span>
        </div>
        <div class="form-group col-sm-5">
          <span class="control-label"><%= match.team1.name %></span>
          <%= f.number_field :team1_score, maxlength: 2, min: 0, max: 99, class: 'score' %>
        </div>
        <div class="form-group col-sm-5">
          <span class="control-label"><%= match.team2.name %></span>
          <%= f.number_field :team2_score, maxlength: 2, min: 0, max: 99, class: 'score' %>
        </div>
      </div>
    <% else %>
      <div class="row">
        <div class="form-group col-sm-2">
          <span>Teams:</span>
        </div>
        <div class="form-group col-sm-5">
          <%= f.collection_select(:team1_id, teams, :id, :name,
            { include_blank: true }, { class: ' team-selector' }) %>
        </div>
        <div class="form-group col-sm-5">
          <%= f.collection_select(:team2_id, teams, :id, :name,
            { include_blank: true }, { class: ' team-selector' }) %>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-sm-2">
          <span>Labels: </span>
        </div>
        <div class="form-group col-sm-5">
          <%= f.text_field :team1_label %>
        </div>
        <div class="form-group col-sm-5">
          <%= f.text_field :team2_label %>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-sm-2">
          <span>Score: </span>
        </div>
        <div class="form-group col-sm-5">
          <span class="control-label">Team 1</span>
          <%= f.number_field :team1_score, maxlength: 2, min: 0, max: 99, class: 'score' %>
        </div>
        <div class="form-group col-sm-5">
          <span class="control-label">Team 2</span>
          <%= f.number_field :team2_score, maxlength: 2, min: 0, max: 99, class: 'score' %>
        </div>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.check_box :ready %>
      <%= f.label :ready, 'Points updated?', class: 'control-label' %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', '#', class: 'btn btn-default', data: { dismiss: 'modal' } %>
  </div>
<% end %>

app/views/admin/matches/_index.html.erb
<table id="matches-table" class="table table-striped" width="100%">
  <thead>
    <tr>
      <th>Number</th>
      <th>Date</th>
      <th>Phase</th>
      <th>Team 1</th>
      <th>Team 1 Score</th>
      <th>Team 2 Score</th>
      <th>Team 2</th>
      <th>Closed?</th>
      <th>Points Updated?</th>
      <th>Actions</th>
    </tr>
  </thead>
  <% matches.each do |match| %>
    <tr>
      <td><%= match.number %></td>
      <td><%= I18n.l match.date, format: :short %></td>
      <td><%= match.phase.name %></td>
      <td><%= match.team1.name if match.team1 %></td>
      <td><%= match.team1_score %></td>
      <td><%= match.team2_score %></td>
      <td><%= match.team2.name if match.team2 %></td>
      <td><%= yes_no_label(match.closed?) %></td>
      <td><%= yes_no_label(match.ready) %></td>
      <td>
        <%= link_to edit_admin_match_path(match), remote: true,
          class: 'btn btn-default btn-sm' do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
        <%= link_to points_admin_match_path(match), remote: true,
          class: 'btn btn-default btn-sm' do %>
          <span class="glyphicon glyphicon-refresh"></span> Run
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<script type="text/javascript">
  $(document).ready(function() {
     $('#matches-table').DataTable({
       retrieve: true,
       iDisplayLength: 64,
       paging: false,
       info: false,
       columns: [
         { type: "num" },
         { type: "string" },
         { type: "string" },
         { type: "string" },
         { orderable: false },
         { orderable: false },
         { type: "string" },
         { type: "string" },
         { type: "string" },
         { orderable: false }
       ]
    });
  });
</script>

app/views/admin/matches/_points.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Match <%= match.number %></h4>
</div>
<div class="modal-body">
  Match predictions updated!
</div>
<div class="modal-footer">
  <%= link_to 'Close', '#', class: 'btn btn-default', data: { dismiss: 'modal' } %>
</div>

app/views/admin/matches/_reload.html.erb
$("div.errors").html("")
<% if match.errors.any? %>
  <% match.errors.full_messages.each do |message| %>
    $("div.errors").append($("<div class='alert alert-danger'/>").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $("#matches-content").html("<%= escape_javascript(render 'index', matches: matches) %>");
  $("#matches-modal").modal("hide");
<% end %>

app/views/admin/matches/edit.js.erb
$("#matches-modal-content")
  .html("<%= escape_javascript(render 'edit', match: @entity_object, teams: @teams) %>");
$("#matches-modal").modal();

app/views/admin/matches/index.html.erb
<%= render 'admin/shared/header', selected: 'matches' %>

<div class="container page">
  <br>
  <div id="matches-content">
    <%= render 'index', matches: @all_entity_objects %>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="matches-modal" role="dialog">
    <div class="modal-dialog modal-md">
      <div id="matches-modal-content" class="modal-content"></div>
    </div>
  </div>
</div>

app/views/admin/matches/points.js.erb
$("#matches-modal-content")
  .html("<%= escape_javascript(render 'points', match: @match) %>");
$("#matches-modal").modal();

app/views/admin/matches/update.js.erb
<%= render 'reload', match: @entity_object, matches: @all_entity_objects %>