config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'authentication' },
    skip: [:registrations, :passwords]

  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

    authenticated do
      root 'predictions#index'
    end
  end

  resources :faq, only: [:index]
  resources :predictions, only: [:index, :show, :update]
  resources :leaderboards, only: [:index, :new, :create, :edit, :update] do
    collection do
      get 'manage'
    end
    member do
      get 'leave'
      get 'leave_confirm'
      get 'members'
      post 'members_confirm'
    end
    resources :invitations, only: [:new, :create] do
      member do
        get 'accept'
        get 'reject'
      end
    end
  end

  namespace :admin do
    resources :matches, only: [:index, :edit, :update] do
      member do
        get 'points'
      end
    end
    resources :users, only: [:index, :edit, :update]
    resources :leaderboards, only: [:index, :edit, :update, :destroy] do
      get 'delete'
    end
  end

end

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <ul class="menu">
          <li>
            <%= link_to('Predictions', predictions_path, class: 'nav-link') %>
          </li>
          <li>
            <%= link_to('Leaderboards', leaderboards_path, class: 'nav-link') %>
          </li>
          <li>
            <%= link_to('FAQ', faq_index_path, class: 'nav-link') %>
          </li>
        </ul>
      </div>
      <div class="col-md-4 text-right">
        <span class="copyright">Quiniela 2018</span>
      </div>
    </div>
  </div>

</footer>

app/views/shared/_messages.html.erb
<header class="messages-header">
  <% flash.each do |type, message| %>
    <% timestamp = Time.now().strftime("%6N") %>
    <div id="flash-<%= timestamp %>" class="alert <%= bootstrap_class_for(type) %> fade in">
      <div class="container">
        <button class="close" data-dismiss="alert">
          <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <i class="glyphicon glyphicon-<%= bootstrap_icon_for(type) %>"></i> <%= message %>
      </div>
    </div>

    <script type="text/javascript">
      $(function() {
        setTimeout(function() { return $("#flash-<%= timestamp %>").fadeOut(); }, 5000);
      });
    </script>
  <% end %>
</header>

app/views/shared/_navbar.html.erb
<header class="nav-header">
  <nav id="navbar-top" class="navbar navbar-default">
    <div class="container">
      <div class="row">
        <div class="navbar-header">
          <%= link_to(root_path, class: 'navbar-brand') do %>
            <%= image_tag('logo-gc.png', alt: 'logo', class: 'img-responsive logo') %>
          <% end %>
        </div>
        <div id="header-menu" class="navbar-right">
          <% if user_signed_in? %>
            <%= image_tag(current_user.picture, alt: 'picture', class: 'user-img') %>
            <span class="user-name">
              <%= current_user.name %> |
              <%= link_to('Log Out', destroy_user_session_path, method: :delete) %>
            </span>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
  <nav id="navbar-menu" class="navbar navbar-default">
    <div class="container">
      <div class="row">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if @active_page == 'predictions' %>">
              <%= link_to('Predictions', predictions_path) %>
            </li>
            <li class="<%= 'active' if @active_page == 'leaderboards' %>">
              <%= link_to('Leaderboards', leaderboards_path) %>
            </li>
            <li class="<%= 'active' if @active_page == 'faq' %>">
              <%= link_to('FAQ', faq_index_path) %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.admin? %>
              <li class="<%= 'active' if @active_page == 'admin' %>">
                <%= link_to('Admin', admin_matches_path) %>
              </li>
            <% end %>
            <li class="<%= 'active' if @active_page == 'manage' %>">
              <%= link_to manage_leaderboards_path do %>
                <span class="glyphicon glyphicon-cog"></span>
                <% if current_user.invitations.size > 0 %>
                  <sup class="invitations-warning">
                    <%= current_user.invitations.size %>
                  </sup>
                <% end %>
              <% end %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>