config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'authentication' },
    skip: [:registrations, :passwords]

  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end

    authenticated do
      root 'predictions#index'
    end
  end

  resources :faq, only: [:index]
  resources :predictions, only: [:index, :show, :update]
  resources :leaderboards, only: [:index, :new, :create, :edit, :update] do
    collection do
      get 'manage'
    end
    member do
      get 'leave'
      get 'leave_confirm'
      get 'members'
      post 'members_confirm'
    end
    resources :invitations, only: [:new, :create] do
      member do
        get 'accept'
        get 'reject'
      end
    end
  end

  namespace :admin do
    resources :matches, only: [:index, :edit, :update] do
      member do
        get 'points'
      end
    end
    resources :users, only: [:index, :edit, :update]
    resources :leaderboards, only: [:index, :edit, :update, :destroy] do
      get 'delete'
    end
  end

end

app/models/leaderboard.rb
class Leaderboard < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :invitations, dependent: :destroy

  belongs_to :owner, class_name: 'User', foreign_key: :owner_id

  validates :name, presence: true, length: { in: 3..40 }, uniqueness: true
  validates :owner_id, presence: true

  scope :active, -> { where(active: true) }
  scope :closed, -> { where(private: true) }
  scope :opened, -> { where(private: false) }

end

app/controllers/admin/leaderboards_controller.rb
class Admin::LeaderboardsController < ApplicationController
  include DefaultCrud

  before_action :authenticate_user!
  before_action :admin_access?
  before_action :set_active_page, only: [:index]

  private

  def set_active_page
    @active_page = 'admin'
  end

  def entity_parameters
    params.require(:leaderboard).permit(:active, :private)
  end

  def load_entity_object_by_id
    @entity_object = entity.find(params[:leaderboard_id])
  end

  def load_all_entity_objects
    @all_entity_objects = entity.order(:name)
  end

end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_active_page, only: [:index]

  def index
    @prediction_sets = users_with_predictions
  end

  private

  def set_active_page
    @active_page = 'leaderboard'
  end

  def users_with_predictions
    PredictionSet
      .where(tournament: tournament).includes(:user)
      .all
      .select { |set| set.user.active }
      .sort_by { |set| [set.points, set.user.name] }
  end

end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :authenticate_user!
  before_action :leaderboards_active_page, only: [:index]
  before_action :manage_active_page, only: [:manage]
  before_action :load_leaderboard,
    only: [:edit, :update, :leave, :leave_confirm, :members, :members_confirm]
  before_action :leaderboards, only: [:create, :update, :leave_confirm, :members_confirm]

  def index
    @general_board ||= PositionBoard.new
    @boards = current_user.leaderboards.map { |leaderboard| PositionBoard.new(leaderboard) }
  end

  def manage
    @leaderboards = current_user.leaderboards
    @invitations = current_user.invitations
  end

  def new
    @leaderboard = Leaderboard.new
  end

  def create
    leaderboard_params = parameters
    leaderboard_params.merge!(owner_id: current_user.id)
    @leaderboard = Leaderboard.create(leaderboard_params)
    if @leaderboard
      @leaderboard.code = SecureRandom.uuid
      @leaderboard.users << current_user
      @leaderboard.save
    end
  end

  def edit
    @leaderboard = Leaderboard.find(params[:id])
  end

  def update
    if @leaderboard.owner == current_user
      @leaderboard.update(parameters)
    else
      @leaderboard.errors.add(:owner, "Invalid")
    end
  end

  def leave_confirm
    @leaderboard.users.delete(current_user)
  end

  def members_confirm
    if @leaderboard.owner == current_user && params.key?(:users)
      user_ids = params.require(:users).permit(ids: [])['ids']
      user_ids.each { |id| @leaderboard.users.delete(User.find(id)) }
    end
  end

  private

  def leaderboards_active_page
    @active_page = 'leaderboards'
  end

  def manage_active_page
    @active_page = 'manage'
  end

  def parameters
    params.require(:leaderboard).permit(:name, :private)
  end

  def leaderboards
    @leaderboards = current_user.leaderboards
  end

  def load_leaderboard
    @leaderboard ||= Leaderboard.find(params[:id])
  end

end

app/views/admin/leaderboards/_delete.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Delete Leaderboard</h4>
</div>
<div class="modal-body">
  <ul class="errors"></ul>
  Are you sure that you want to delete: <b><%= leaderboard.name %></b>?
</div>
<div class="modal-footer">
  <%= link_to 'Cancel', '#', class: 'btn btn-default', data: { dismiss: 'modal' } %>
  <%= link_to 'Delete Leaderboard', admin_leaderboard_path(leaderboard),
    method: :delete, remote: true,
    class: 'btn btn-danger' %>
</div>

app/views/admin/leaderboards/_edit.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Edit Leaderboard</h4>
</div>
<div>
  <%= render 'form', leaderboard: leaderboard %>
</div>

app/views/admin/leaderboards/_form.html.erb
<%= form_for [:admin, leaderboard], remote: true, html: { style: 'display:inline;' } do |f| %>
  <div class="modal-body">
    <div class="errors"></div>
    <div class="form-group">
      <%= f.label :name, class: 'control-label' %>
      <%= f.text_field :name, disabled: true, class: 'control-label' %>
    </div>
    <div class="form-group">
      <%= f.check_box :active %>
      <%= f.label :active, class: 'control-label' %>
    </div>
    <div class="form-group">
      <%= f.check_box :private %>
      <%= f.label :private, class: 'control-label' %>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', '#', class: 'btn btn-default', data: { dismiss: 'modal' } %>
  </div>
<% end %>

app/views/admin/leaderboards/_index.html.erb
<table id="leaderboards-table" class="table table-striped" width="100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Owner</th>
      <th>Members</th>
      <th>Active?</th>
      <th>Private?</th>
      <th>Actions</th>
    </tr>
  </thead>
  <% leaderboards.each do |leaderboard| %>
    <tr>
      <td><%= leaderboard.name %></td>
      <td><%= leaderboard.code %></td>
      <td><%= leaderboard.owner.name %></td>
      <td><%= leaderboard.users.size %></td>
      <td><%= yes_no_label(leaderboard.active) %></td>
      <td><%= yes_no_label(leaderboard.private) %></td>
      <td>
        <%= link_to edit_admin_leaderboard_path(leaderboard), remote: true,
          class: 'btn btn-default btn-sm' do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
        <%= link_to admin_leaderboard_delete_path(leaderboard), remote: true,
          class: 'btn btn-danger btn-sm' do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<script type="text/javascript">
  $(document).ready(function() {
     $('#leaderboards-table').DataTable({
       retrieve: true,
       iDisplayLength: 50,
       columns: [
         { type: "string" },
         { type: "string" },
         { type: "string" },
         { type: "num" },
         { type: "string" },
         { type: "string" },
         { orderable: false }
       ]
    });
  });
</script>

app/views/admin/leaderboards/_reload.html.erb
$("div.errors").html("")
<% if leaderboard.errors.any? %>
  <% leaderboard.errors.full_messages.each do |message| %>
    $("div.errors").append($("<div class='alert alert-danger'/>").html("<%= message.html_safe %>"));
  <% end %>
<% else %>
  $("#leaderboards-content")
    .html("<%= escape_javascript(render 'index', leaderboards: leaderboards) %>");
  $("#leaderboards-modal").modal("hide");
<% end %>

app/views/admin/leaderboards/delete.js.erb
$("#leaderboards-modal-content")
  .html("<%= escape_javascript(render 'delete', leaderboard: @entity_object ) %>");
$("#leaderboards-modal").modal();

app/views/admin/leaderboards/destroy.js.erb
<%= render 'reload', leaderboard: @entity_object, leaderboards: @all_entity_objects %>

app/views/admin/leaderboards/edit.js.erb
$("#leaderboards-modal-content")
  .html("<%= escape_javascript(render 'edit', leaderboard: @entity_object) %>");
$("#leaderboards-modal").modal();

app/views/admin/leaderboards/index.html.erb
<%= render 'admin/shared/header', selected: 'leaderboards' %>

<div class="container page">
  <br>
  <div id="leaderboards-content">
    <%= render 'index', leaderboards: @all_entity_objects %>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="leaderboards-modal" role="dialog">
    <div class="modal-dialog modal-md">
      <div id="leaderboards-modal-content" class="modal-content"></div>
    </div>
  </div>
</div>

app/views/admin/leaderboards/update.js.erb
<%= render 'reload', leaderboard: @entity_object, leaderboards: @all_entity_objects %>